UP = 'UP'
DOWN = 'DOWN'
LEFT = 'LEFT'
RIGHT = 'RIGHT'
ACTIONS = [UP, DOWN, LEFT, RIGHT]

DIRECTION_VECTORS = {
    UP: (-1,  0),
    DOWN: (1,  0),
    LEFT: (0, -1),
    RIGHT: (0,  1),
}

BOARD_SIZE = 10

REWARD_GREEN = 25
REWARD_RED = -25
REWARD_DEATH = -100
REWARD_STEP = -2.5

THREAT_DANGER = 'danger'
THREAT_GREEN = 'green'
THREAT_RED = 'red'

DIST_NEAR = 'near'
DIST_MEDIUM = 'medium'
DIST_FAR = 'far'

CELL_EMPTY = '0'
CELL_HEAD = 'H'
CELL_BODY = 'S'
CELL_GREEN = 'G'
CELL_RED = 'R'
CELL_WALL = 'W'
